# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cucumber-json}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jesse Newland"]
  s.date = %q{2010-05-19}
  s.description = %q{A cucumber formatter that outputs JSON}
  s.email = %q{jnewland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "Rakefile",
     "Readme.md",
     "cucumber-json.gemspec",
     "examples/features.json",
     "features/formatter.feature",
     "features/step_definitions/cucumber_steps.rb",
     "features/step_definitions/custom_steps.rb",
     "features/support/env.rb",
     "lib/cucumber/formatter/json.rb",
     "lib/cucumber/formatter/json/version.rb"
  ]
  s.homepage = %q{http://github.com/jnewland/cucumber-json}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A cucumber formatter that outputs JSON}
  s.test_files = [
    "features/formatter.feature",
     "features/step_definitions",
     "features/step_definitions/cucumber_steps.rb",
     "features/step_definitions/custom_steps.rb",
     "features/support",
     "features/support/env.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cucumber>, ["~> 0.7.3"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.3"])
    else
      s.add_dependency(%q<cucumber>, ["~> 0.7.3"])
      s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
    end
  else
    s.add_dependency(%q<cucumber>, ["~> 0.7.3"])
    s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
  end
end

